plugins {
    id 'java-library'
}

repositories {
    mavenCentral()
}

sourceSets {
    main {
        java {
            srcDir rootProject.file('src/main/java')
            include 'cn/net/rms/confluxmap/core/**'
            include 'cn/net/rms/confluxmap/nativepredict/**'
            include 'cn/net/rms/confluxmap/server/ChunkColumnSource.java'
            include 'cn/net/rms/confluxmap/server/ChunkColumnSummarizer.java'
            include 'cn/net/rms/confluxmap/server/CompanionPolicy.java'
            include 'cn/net/rms/confluxmap/server/LiveChunkSummaryCache.java'
            include 'cn/net/rms/confluxmap/server/PatchBuilder.java'
            include 'cn/net/rms/confluxmap/server/PatchDispatcher.java'
            include 'cn/net/rms/confluxmap/server/PlayerBudget.java'
            include 'cn/net/rms/confluxmap/server/ProgressivePatchTask.java'
            include 'cn/net/rms/confluxmap/server/ProgressiveSourceStamps.java'
            include 'cn/net/rms/confluxmap/server/ProgressiveSummaryGrid.java'
            include 'cn/net/rms/confluxmap/server/RegionPatchBuilder.java'
            include 'cn/net/rms/confluxmap/server/ServerConfig.java'
            include 'cn/net/rms/confluxmap/server/SummaryDiskCache.java'
            include 'cn/net/rms/confluxmap/server/SummaryTile.java'
            include 'cn/net/rms/confluxmap/server/SummaryView.java'
            include 'cn/net/rms/confluxmap/server/SyncPerformanceFormatter.java'
            include 'cn/net/rms/confluxmap/server/SyncPerformanceMonitor.java'
            include 'cn/net/rms/confluxmap/server/TilePresence.java'
            include 'cn/net/rms/confluxmap/server/shared/SharedWaypointIo.java'
            include 'cn/net/rms/confluxmap/server/shared/SharedWaypointPersistence.java'
            include 'cn/net/rms/confluxmap/server/shared/SharedWaypointService.java'
            include 'cn/net/rms/confluxmap/server/shared/SharedWaypointSessionHandler.java'
            include 'cn/net/rms/confluxmap/server/shared/SharedWaypointStore.java'
            include 'cn/net/rms/confluxmap/server/shared/SharedWaypointValidator.java'
        }
    }
    test {
        java.srcDir rootProject.file('companion-common/src/test/java')
    }
}

dependencies {
    compileOnly 'com.google.code.gson:gson:2.13.2'
    compileOnly 'org.apache.logging.log4j:log4j-api:2.25.3'
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

java {
    sourceCompatibility = JavaVersion.VERSION_16
    targetCompatibility = JavaVersion.VERSION_16
}

test {
    useJUnitPlatform()
}
