# velocity.command.server-available from PaperMC/Velocity.
# Source commit: 2676520c6a54bac0529544793c982dd701b338d9 (GPL-3.0)
default=Available servers:
ar_SA=السيرفرات المتاحة:
bg_BG=Налични сървъри:
cs_CZ=Dostupné servery:
da_DK=Tilgængelige servere:
de_DE=Verfügbare Server:
es_ES=Servidores disponibles:
et_EE=Saadaolevad serverid:
fi_FI=Saatavilla olevat palvelimet:
fr_FR=Serveurs disponibles :
he_IL=שרתים זמינים:
hu_HU=Elérhető szerverek:
it_IT=Server disponibili:
ja_JP=利用可能なサーバー:
ko_KR=사용 가능한 서버:
nb_NO=Tilgjengelige servere:
nl_NL=Beschikbare servers:
nn_NO=Tilgjengelege sørvarar:
pl_PL=Dostępne serwery:
pt_BR=Servidores disponíveis:
ro_RO=Available servers:
ru_RU=Доступные серверы:
sk_SK=Dostupné servery:
sq_AL=Serverat e disponueshëm:
sr_CS=Dostupni serveri:
sr_Latn=Dostupni serveri:
sv_SE=Tillgängliga servrar:
tl_PH=Magagamit na mga serbidor:
tr_TR=Müsait sunucular:
uk_UA=Доступні сервери:
vi_VN=Máy chủ có sẵn:
zh_CN=可用的服务器：
zh_HK=可用的伺服器：
zh_TW=可用的伺服器：
