# velocity.command.server-current-server from PaperMC/Velocity.
# Source commit: 2676520c6a54bac0529544793c982dd701b338d9 (GPL-3.0)
default=You are currently connected to <arg:0>.
ar_SA=أنت الآن متصل بـ<arg:0>
bg_BG=В момента сте свързан към <arg:0>.
cs_CZ=Právě jsi připojen k serveru <arg:0>.
da_DK=Du er i øjeblikket forbundet til <arg:0>.
de_DE=Du bist derzeit mit <arg:0> verbunden.
es_ES=Estás conectado a <arg:0>.
et_EE=Sa oled hetkel ühendatud serveriga <arg:0>.
fi_FI=Olet tällä hetkellä yhdistettynä palvelimeen <arg:0>.
fr_FR=Vous êtes actuellement connecté(e) à <arg:0>.
he_IL=אתה מחובר כעת ל- <arg:0>.
hu_HU=Jelenleg a(z) <arg:0> szerveren tartózkodsz.
it_IT=Sei già connesso a <arg:0>.
ja_JP=現在 <arg:0> に接続しています。
ko_KR=현재 <arg:0>에 연결되어 있습니다.
nb_NO=Du er for øyeblikket tilkoblet <arg:0>.
nl_NL=Je bent op dit moment verbonden met <arg:0>.
nn_NO=Du er for augneblinken tilkopla <arg:0>.
pl_PL=Jesteś obecnie połączony z <arg:0>.
pt_BR=Você está atualmente conectado a <arg:0>.
ro_RO=You are currently connected to <arg:0>.
ru_RU=На данный момент вы подключены к серверу <arg:0>.
sk_SK=Aktuálne si pripojený na <arg:0>.
sq_AL=Aktualisht jeni i lidhur me <arg:0>.
sr_CS=Trenutno ste povezani na <arg:0>.
sr_Latn=Trenutno ste povezani na <arg:0>.
sv_SE=Du är just nu ansluten till <arg:0>.
tl_PH=Nakakonekta ka sa <arg:0>.
tr_TR=Şu anda <arg:0> sunucusuna bağlısın.
uk_UA=Зараз ви приєднані до сервера <arg:0>.
vi_VN=Hiện bạn đang kết nối đến <arg:0>.
zh_CN=您已连接至 <arg:0>。
zh_HK=您已連接至 <arg:0>。
zh_TW=您已連線到 <arg:0>。
